# Generated by Django 4.1.7 on 2023-03-01 13:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=150)),
                ('editora', models.CharField(max_length=150)),
                ('previa', ckeditor_uploader.fields.RichTextUploadingField()),
                ('capa', models.FileField(upload_to='capa/')),
                ('arquivo', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
